# mini project2_02_20191519 이수현
## human Activity Recognition

### 20191519 이수현

In [11]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Is this notebook running on Colab or Kaggle?
IS_COLAB = "google.colab" in sys.modules
IS_KAGGLE = "kaggle_secrets" in sys.modules

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "classification"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [12]:
import numpy as np
import pandas as pd

input_file = "train.csv"
df_train = pd.read_csv(input_file)

In [13]:
data_train = df_train.to_numpy()
data_train

array([[0.28858451, -0.020294171, -0.13290514, ..., -0.058626924, 1,
        'STANDING'],
       [0.27841883, -0.016410568, -0.12352019, ..., -0.054316717, 1,
        'STANDING'],
       [0.27965306, -0.019467156, -0.11346169, ..., -0.049117815, 1,
        'STANDING'],
       ...,
       [0.27338737, -0.017010616, -0.045021828, ..., 0.040811188, 30,
        'WALKING_UPSTAIRS'],
       [0.28965416, -0.018843044, -0.15828059, ..., 0.025339478, 30,
        'WALKING_UPSTAIRS'],
       [0.35150347, -0.012423118, -0.20386717, ..., 0.036694843, 30,
        'WALKING_UPSTAIRS']], dtype=object)

In [14]:
data_train.shape

(7352, 563)

In [15]:
X_train = data_train[:, :-2]
X_train

array([[0.28858451, -0.020294171, -0.13290514, ..., -0.84124676,
        0.17994061, -0.058626924],
       [0.27841883, -0.016410568, -0.12352019, ..., -0.8447876,
        0.18028889, -0.054316717],
       [0.27965306, -0.019467156, -0.11346169, ..., -0.84893347,
        0.18063731, -0.049117815],
       ...,
       [0.27338737, -0.017010616, -0.045021828, ..., -0.77913261,
        0.24914484, 0.040811188],
       [0.28965416, -0.018843044, -0.15828059, ..., -0.78518142,
        0.24643223, 0.025339478],
       [0.35150347, -0.012423118, -0.20386717, ..., -0.78326693,
        0.24680852, 0.036694843]], dtype=object)

In [16]:
y_train = data_train[:, -1]
y_train

array(['STANDING', 'STANDING', 'STANDING', ..., 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'WALKING_UPSTAIRS'], dtype=object)

# Adaboost Classifier

In [44]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier 

ada_clf = AdaBoostClassifier(
    RandomForestClassifier(n_jobs=-1, random_state=42), 
    algorithm="SAMME.R", learning_rate=0.01, random_state=42)

ada_clf.fit(X_train, y_train)

AdaBoostClassifier(base_estimator=RandomForestClassifier(n_jobs=-1,
                                                         random_state=42),
                   learning_rate=0.01, random_state=42)

## RandomForest

In [1]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier 

rnd_clf = RandomForestClassifier(n_jobs=-1, random_state=42)

rnd_clf.fit(X_train, y_train)

NameError: name 'X_train' is not defined

# 최종 점수

In [45]:
from sklearn.model_selection import cross_val_score

cross_val_score(ada_clf, X_train, y_train, cv=10, scoring="accuracy")

array([0.94429348, 0.88451087, 0.97414966, 0.85034014, 0.94693878,
       0.88571429, 0.9537415 , 0.98231293, 0.95646259, 0.95510204])

In [46]:
np.mean([0.94429348, 0.88451087, 0.97414966, 0.85034014, 0.94693878, 0.88571429, 0.9537415 , 0.98231293, 0.95646259, 0.95510204])

0.933356628

#### 결과: 0.933356628