# mini_proj_01_20191519 이수현
## Handwritten Digit Classfication

In [1]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)


IS_COLAB = "google.colab" in sys.modules
IS_KAGGLE = "kaggle_secrets" in sys.modules


import sklearn
assert sklearn.__version__ >= "0.20"


import numpy as np
import os


np.random.seed(42)


%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)


PROJECT_ROOT_DIR = "."
CHAPTER_ID = "classification"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

## pandas의 read_csv를 이용해 훈련셋 읽기

In [2]:
import numpy as np
import pandas as pd

input_file = "emnist-digits-train.csv"
df_train = pd.read_csv(input_file, header=None)

In [3]:
data_train = df_train.to_numpy()
data_train

array([[8, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [4]:
data_train.shape

(240000, 785)

In [5]:
X_train = data_train[:, 1:]
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [6]:
y_train = data_train[:, 0]
y_train

array([8, 9, 6, ..., 1, 1, 0], dtype=int64)

In [7]:
from sklearn.linear_model import SGDClassifier  # sgd 분류기
from sklearn.ensemble import RandomForestClassifier  # randomforest 분류기
from sklearn.svm import LinearSVC
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import VotingClassifier
# from sklearn.linear_model import LogisticRegression

# sgd 분류기
# sgd_clf = SGDClassifier(max_iter=5, tol=-np.infty,  random_state=42)
# sgd_clf.fit(X_train, y_train)

# randomforest 분류기
rad_clf = RandomForestClassifier(n_estimators=500, random_state=42)
rad_clf.fit(X_train, y_train)



RandomForestClassifier(n_estimators=500, random_state=42)

## 최종 점수

In [9]:
from sklearn.model_selection import cross_val_score

cross_val_score(rad_clf, X_train, y_train, cv=10, scoring="accuracy")

array([0.98225   , 0.98216667, 0.98254167, 0.981625  , 0.9805    ,
       0.98254167, 0.98229167, 0.982625  , 0.98145833, 0.982125  ])

In [12]:
np.mean([0.98225   , 0.98216667, 0.98254167, 0.981625  , 0.9805   ,0.98254167, 0.98229167, 0.982625  , 0.98145833, 0.982125  ])

0.982012501

#### 결과: 0.982012501